//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndtoEnd.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int Id { get; set; }
        public decimal Change { get; set; }
        public decimal PercentChange { get; set; }
        public decimal Last { get; set; }
        public decimal Shares { get; set; }
        public string Symbol { get; set; }
        public System.DateTime RetrievalDateTime { get; set; }
        public string Company { get; set; }
    
        public virtual Securities_MutualFund Securities_MutualFund { get; set; }
        public virtual Securities_Stock Securities_Stock { get; set; }
    }
}
